# Generated by Django 3.1.6 on 2021-02-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
